common: &common
  adapter: postgresql
  username: webadmin
  password: SrgOxHrvbi

development:
  <<: *common
  host: localhost
  database: contacal_development
  password: postgres

test:
  <<: *common
  database: contacal_test

production:
  <<: *common
  database: contacal_production
