common: &common
  adapter: postgresql
  username: postgres
  password: 

development:
  <<: *common
  database: contacal_development

test:
  <<: *common
  database: contacal_test

production:
  <<: *common
  database: contacal_production