common: &common
  adapter: postgresql
  username: postgres
  password: 

development:
  <<: *common
  host: localhost
  database: contacal_development
  password: postgres

test:
  <<: *common
  database: contacal_test

production:
  <<: *common
  database: contacal_production
  username: webadmin
  password: rthrm3n2ui  
  host: 10.70.2.11
